### ISSUE TITLE
Incorrect zimming message

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#100]
I requested a zim file from zimit.kiwix.org and I got the standard "please wait while zimming" banner while it was doing its thing. I noticed however that the message says `Do not close this window without this bookmark or you won't be able to download your ZIM since you did not provide an email.` This is incorrect as I did, in fact, provide an email (which the system accepted as I got a notification in my email).

**Comment by benoit74** [comment]
Nice catch, message is correct when you are waiting in the queue, but not correct anymore when you task is being processed ... 🤦🏻‍♂️
