### ISSUE TITLE
Add a link to Webrecorder somewhere?

### ISSUE THREAD

**Issue by ikreymer** [openzim/zimit-frontend#15]
Just a small request, perhaps there could be text somewhere on the page that says 'Developed by Kiwix and Webrecorder' or 'powered by browsertrix crawler' or something like that and perhaps have link to the https://github.com/webrecorder/browsertrix-crawler repo? Or perhaps in the FAQ?
Not sure what would best exactly as I see the UI is still in development.

**Comment by kelson42** [comment]
I'm in favour of this.

**Comment by rgaudin** [comment]
Awaiting exact sentence and where to put it…

**Comment by kelson42** [comment]
```
Powered by <a href='https://kiwix.org'> with the help of <a href="https://webrecorder.net">Webrecorder</a>, thanks to a <a href="https://www.mozilla.org/moss/">Mozilla Open-Source Support</a> Award :heart:
```
