### ISSUE TITLE
Is there any way to know who requesters are?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#23]
There's a privacy / liability issue of course that would want us not to know this, but conversely we could identify freeriders and see if any one user is responsible for the majority of requests.

Bonus question: could we easily block someone from filing request for a given period of time (either block the IP or the email address)?

**Comment by kelson42** [comment]
@Popolechien You can have a clue about who uses the youzim.it service with the web stats. For not this is not possible to ban someone based on his IP.

**Comment by rgaudin** [comment]
As you know, there is no *User* in the project and every request is treated the same. We don't record IP addresses.
You might consider the email address to which we send notifications to *identify* requests but that's limited and certainly not appropriate for restrictions.

We should probably include details about what we do and for how long with user's data (in the FAQ), to comply with GDPR

We should also keep in mind that anyone can input anyone else's email address and thus create unsolicited messages
