### ISSUE TITLE
How hard would it be to create a zimit browser extension?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#24]
Rather than having users comme to youzim.it, we could have zimit "come to them" via a browser extension. Click and it would zim up the website currently displayed in the tab?

**Comment by kelson42** [comment]
What would be the feature(s)?

**Comment by Popolechien** [comment]
Literally what I just described: a button on top of the browser that you click and that sends a request to youzim.it (assuming at this point that it has access to the user's email address).

**Comment by kelson42** [comment]
@Popolechien This is pretty easy technically, but I strongly suspect that to make this extension really usable (properly integrated with the browser), we need more than you think of for the moment.

**Comment by rgaudin** [comment]
As @kelson42 said it's relatively easy to create such an extension but it would be a new product that need to be polished, improved and maintained. Who is going to use it? Who is already using youzimit ? How many of them are using it frequently? I doubt we already have numbers that would justify this ATM. Especially given the alternative is clicking a bookmark and pasting a URL…

One could even write a bookmarklet to to what you are referring to.

**Comment by Popolechien** [comment]
> it would be a new product that need to be polished, improved and maintained

Oof, I'm not thinking that far. The question was raised during a presentation meeting and I wanted to see the feasibility. Got my answer.
