### ISSUE TITLE
Update "How do I read my Zim files" section

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#30]
Current text 

You will need a Zim file reader. This usually means [Kiwix](https://kiwix.org/), which is available on [desktop computers, mobile devices, and more](https://www.kiwix.org/en/download/). Currently only Kiwix-serve and Kiwix-Android can read all Zimit-generated files. If using Kiwix-Desktop for Microsoft Windows and GNU/Linux, then you will need to configure it as a Kiwix-serve instance in the settings. We expect most platforms to be upgraded by the end of 2021.

New text

Currently, Zimit files can only be read with Kiwix-serve. If you are using Kiwix-Desktop for Microsoft Windows and GNU/Linux, it is possible to set it up to run Kiwix-serve from the settings.

**Comment by rgaudin** [comment]
Isn't kiwix-android reading zimit files as well?

**Comment by kelson42** [comment]
I propose to do that, post Zimit 2.0.

**Comment by kelson42** [comment]
With Zimit 2.0 it will work out of the box. This ticket does not make sense anymore.

**Comment by benoit74** [comment]
Don't we still need to update the text after Zimit 2.0 ? 

![image](https://github.com/openzim/zimit-frontend/assets/7102089/52cd34a8-bcee-47d7-9a50-75b8d95cf758)

The text basically says that you need kiwix-serve, which won't be true after Zimit 2.0

**Comment by rgaudin** [comment]
Indeed

**Comment by realeatham** [comment]
Make sure to include that not just kiwix desktop in the text
