### ISSUE TITLE
Move service from youzim.it to zimit.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#31]
It's all in the title, following the (re)branding discussion.

**Comment by rgaudin** [comment]
What should be done with youzim.it ; just a regular redirection to zimit.kiwix.org until the domain expires?

**Comment by Popolechien** [comment]
Sounds good to me

**Comment by kelson42** [comment]
@benoit74 @rgaudin This decision is old and part of the [rebranding effort strategy](https://github.com/kiwix/overview/wiki/Branding). Time to implement it, maybe this can be done as part of the operation routine?

I would keep the domain `youzim.it` for a few years and make a redirect. Just my opinion.

**Comment by kelson42** [comment]
@rgaudin @benoit74 Can we implement this now?
