### ISSUE TITLE
Can you provide some documentation for those wanting to self host

### ISSUE THREAD

**Issue by catduckgnaf** [openzim/zimit-frontend#34]
I would love to self host zimit-frontend.

there is absolutely zero documentation, this is a great tool, and I would really love documentation so I can set it up.

I can't even find that ports or variables are needed, etc. This could be such a great tool for so many people to install.

**Comment by rgaudin** [comment]
zimit-frontend is a complex tool. It's comprised of:

[**zimfarm**](https://github.com/openzim/zimfarm/)
- A mongodb database container
- A dispatcher API container
- A _frontend_ container (not youzim.it one, the one for monitoring)
- One or more worker containers (on the same machine or others). Those are the ones creating the ZIM files

**zimit-frontend**
- A frontend container

I don't think this as any value for the occasional ZIM creator. It's only worth the effort if you want to deploy a SaaS like youzim.it.

Anyway, the complete configuration is at https://github.com/kiwix/k8s/tree/main/zimit

**Comment by catduckgnaf** [comment]
I really wish you would make it easier for users to create and edit their own zims. I feel this would really build the community.....

**Comment by rgaudin** [comment]
Anybody can you youzim.it. If reaching limits, one can still use command-line [zimit](https://github.com/openzim/zimit) which is what is done eventually, behind the curtain. Check zimit's README. it's used mostly via docker
