### ISSUE TITLE
Zimfarm does not show list of contents in pipeline

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#36]
If I go to https://farm.youzim.it/pipeline/filter-todo, the website that should be listed in the `schedule` column are not indicated.
![Capture d’écran 2023-06-09 à 16 19 45](https://github.com/openzim/zimit-frontend/assets/21675885/79b5ea9e-a2c6-4197-aeb3-12e6ddcbb8d9)

Note seeing this on farm.openzim.org, being logged in or not does not make any difference.

**Comment by rgaudin** [comment]
https://github.com/openzim/zimfarm/issues/797
