### ISSUE TITLE
ZIM filename does not match requirements

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit-frontend#43]
When creating a schedule, the provided filename does not match our convention and is refused by the Zimfarm since https://github.com/openzim/zimfarm/pull/865 has been merged.

**Comment by rgaudin** [comment]
youzim.it filenames have already been debated a lot. @Popolechien have been very insistent on the filenames being user-centered given those are not in the catalog. Including the unique ID (so we can safely store them in a flat folder) required some convincing.

Additionally, the period makes zero sense in the context of youzim.it: it's creation is manual and not periodic and this month-period would only bring confusion.

I thus think option 1 is more practical. I don't recall how wp1 filenames are constructed. They might not fit the pattern neither

**Comment by benoit74** [comment]
WP1 is not impacted from what I looked after because we validate only output, description, long description and other basic range / oneOf validations.

OK for option 1 if this is what fits you.

**Comment by rgaudin** [comment]
@Popolechien can confirm whether it still makes sense to him

**Comment by Popolechien** [comment]
yes.

**Comment by benoit74** [comment]
I've opened upstream issue since nothing has to be done in zimit-frontend in the end: https://github.com/openzim/zimfarm/issues/867
