### ISSUE TITLE
Email adress is not a required input

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit-frontend#50]
For now, it is possible to request a ZIM without entering an email address.

While "it works" (if the user keeps the page opened without touching anything until the ZIM is ready, he will be displayed the download link), there is very little probability that it will lead to an enjoyable experience for the user. If the user moves out of the page or simply hit refresh, everything is lost, i.e. the zimfarm will process the task, the ZIM will be uploaded but the user will never get access to the ZIM.

Is this an intentional behavior?

**Comment by rgaudin** [comment]
It is. I believe the page clearly warns about it

**Comment by benoit74** [comment]
Believe me, it works without email.

I found records without emails in the DB while trying to check if someone is abusing youzim.it, and I did my own test, nothing prevents you to request a ZIM without entering your email ; it only warns you if your email is invalid.

**Comment by rgaudin** [comment]
> Believe me, it works without email.


I hope so since this is the purpose of this tool! 

I don't recall exactly but we might have added email as a convenience for those willing to to relax that URL keeping requirement.

**Comment by benoit74** [comment]
Oh, so I got it wrong, when you said "It is", it was a reply to my question ... obvious ... so it is intentional. OK, let's close this then.
