### ISSUE TITLE
FastAPI is not redirecting properly when behind a reverse proxy

### ISSUE THREAD

**Issue by benoit74** [openzim/zimit-frontend#73]
When the API backend receives a `POST /requests/`, it should redirect automatically to `/requests` which is the proper endpoint.

This works well in dev and http, but does not work when FastAPI is behind a reverse-proxy handling the TLS termination. In such a case, while the original request was done in HTTPS, FastAPI has no idea about it and hence downgrade the protocol to HTTP. 

Which in turns cause an issue with the browser which refuses to downgrade an HTTPS call to HTTP (for good reasons).

This typically happens in our k8s setup. Short term solution is already implemented: we ensure the frontend does the POST on proper URL !

However it would help to properly solve the issue for the long term.

Maybe this is not a FastAPI / zimit-frontend issue but only our nginx reverse proxy which is not properly passing required information.

**Comment by rgaudin** [comment]
We should not post to `/requests/`. the redirection is there to assist with historical bad habits. I think we should not change our configuration and use it as a hint that our frontend uses incorrect URL/path.

We could also disable the auto redirection in fastAPI to catch early on.

**Comment by benoit74** [comment]
I like the idea of disabling the auto redirection in fastAPI to catch early on. I'll open another issue then.
