### ISSUE TITLE
Youzim.it seems not to be updated 

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit-frontend#8]
Look at https://stats.kiwix.org/index.php?module=CoreHome&action=index&idSite=11&period=day&date=yesterday&updated=1#?idSite=11&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

**Comment by rgaudin** [comment]
Can you be more specific ? What is there to see and/or understand?

<img width="515" alt="Screen Shot 2020-12-14 at 09 21 21" src="https://user-images.githubusercontent.com/57929/102063311-c7966d80-3ded-11eb-9fb5-8f2cc91b8c85.png">

I don't know matomo much but the table tells me it's being updated. Keep in mind that nobody uses this URL and that uBlock Origin blocks this by default so we shouldn't expect much stats.
