### ISSUE TITLE
Download email missing download links

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit-frontend#90]
This might be due to the user using dark mode (though I doubt it) but someone reported that their zimit download confirmation email looked like this

![Image](https://github.com/user-attachments/assets/becadb86-acb0-4c38-b50d-16d5f5d69cfc)

**Comment by Popolechien** [comment]
Ah, the mistery deepens as the job looks like it is https://farm.zimit.kiwix.org/pipeline/0f30d932-dd33-49b7-97a6-b975e1a4f0e7 and it does not have any file to show for it.

**Comment by rgaudin** [comment]
zimit issue as there was a scraping error which was reported as success

```
ERROR:Main URL returned an unprocessable HTTP code: 403
```

**Comment by rgaudin** [comment]
warc2zim even

**Comment by benoit74** [comment]
Definitely something broken between zimit/warc2zim, I'll check.

But we should as well not send a success email when no files have been produced, this would have hidden the underlying problem but still makes sense.

**Comment by benoit74** [comment]
I confirm that:
- we have an issue in zimit
- we have an issue in zimit-frontend (at least it could / should detect when no files have been produced)

I did not achieved to reproduce the issue in Browsertrix crawler.

**Comment by benoit74** [comment]
I propose to not change anything in zimit-frontend, but implement https://github.com/openzim/zimfarm/pull/1045

**Comment by benoit74** [comment]
After all, fixing this in zimit-frontend is also mostly straightforward ^^ better fixed in 3 places than none 🤣
