### ISSUE TITLE
"How do I read my ZIM files?" link takes you to example image

### ISSUE THREAD

**Issue by JeffersonBledsoe** [openzim/zimit-frontend#98]
Within the `How do I read my ZIM files?` section is a link with the text `desktop computers, mobile devices, and more`. This takes you to https://www.kiwix.org/en/download/ which gives you a 301 redirect to https://kiwix.org/en/latest-annual-report/download/ which also has a 301 to https://kiwix.org/wp-content/uploads/2023/07/download.webp which is just a placeholder image

**Comment by benoit74** [comment]
Thank you for reporting that !

@Popolechien is the link wrong (and which one should we use then) or is it just a bad setup in Wordpress you want to fix?

**Comment by rgaudin** [comment]
We really need a better tracking/management of permalinks.

**Comment by kelson42** [comment]
> We really need a better tracking/management of permalinks.

Yes, we need a HTTP 404 monitoring solution (linked to our monitoring) for our Web sites. I wonder if we don't have already an issue for that becauae this is a topic I have studied in the past.
